import Link from "next/link";
import { CTA, Eyebrow, SectionIntro, Status } from "@/components/ui";
import { HeroWave } from "@/components/hero-wave";
import { LineIcon } from "@/components/icons";
import { principles, products, updates } from "@/data/site";

export default function Home() {
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><Eyebrow>One Better Labs · AI product studio</Eyebrow><h1>Building AI products that help people make <span>one better decision.</span></h1><p>We create beautifully simple AI-powered products that solve real-world problems, reduce cognitive load and help people move forward with clarity.</p><div className="button-row"><Link className="button" href="#products">Explore our products <span>→</span></Link><Link className="button button-ghost" href="/our-story">Meet OB Labs <span>↗</span></Link></div></div><HeroWave /></div><div className="hero-side-note">Small decisions. Meaningful change.</div></section>
    <section id="products" className="products-home"><div className="container"><SectionIntro eyebrow="Our products" title="Practical AI. Built around people." text="Three products shaped by different real-world problems, connected by one belief: technology should leave people feeling more capable than before."/><div className="products-grid">{products.map(p=><article className="product-card" key={p.slug}><div className="product-card-head"><span>{p.number}</span><Status>{p.status}</Status></div><div className="mini-visual"><LineIcon name={p.slug} size={55}/></div><h3>{p.name}</h3><p className="positioning">{p.positioning}</p><p>{p.summary}</p><Link href={`/products/${p.slug}`}>Explore {p.name} <span>↗</span></Link></article>)}</div></div></section>
    <section id="philosophy" className="philosophy"><div className="container philosophy-layout"><SectionIntro eyebrow="Our philosophy" title="Great software doesn’t need to be complicated." text="We build beautifully simple AI-powered products that reduce cognitive load, create clarity and help people make one better decision."/><div className="principles">{principles.map(p=><div className="principle" key={p.title}><div className="principle-icon"><LineIcon name={p.icon}/></div><div><h3>{p.title}</h3><p>{p.text}</p></div></div>)}</div></div></section>
    <section className="why"><div className="container why-layout"><p className="why-quote">The best technology should disappear into the moment it helps.</p><div className="why-copy"><Eyebrow>Why we build</Eyebrow><p>It should understand the problem, remove unnecessary friction and leave the person feeling more capable than before.</p><p>We start with real moments of uncertainty—not technology searching for a use case—and work backwards towards the simplest useful answer.</p><Link className="button button-ghost" href="/our-story">Read our story <span>→</span></Link></div></div></section>
    <section className="portfolio"><div className="container"><SectionIntro eyebrow="One connected portfolio" title="Different moments. The same way forward." text="Every OB Labs product helps turn complexity into a clear, manageable next decision."/><div className="portfolio-line">{products.map(p=><div className="journey-item" key={p.slug}><span className="journey-dot">{p.number}</span><h3>{p.name}</h3><p>{p.slug==="cueiq"?"Better decisions at the pool table.":p.slug==="arlo"?"A next step that feels manageable.":"Ideas turned into consistent action."}</p></div>)}</div></div></section>
    <section className="updates-home"><div className="container"><SectionIntro eyebrow="From the lab" title="Notes from the journey."/><div className="updates-list">{updates.map(u=><Link href={`/updates/${u.slug}`} className="update-row" key={u.slug}><small>{u.category}</small><h3>{u.title}</h3><span>↗</span></Link>)}</div></div></section>
    <CTA />
  </>;
}
