import Image from "next/image";
import Link from "next/link";

const playStoreUrl = "https://play.google.com/store/search?q=Arlo%20ADHD%20One%20Better%20Labs&c=apps";
const features = [
  ["AI Conversations", "Natural conversations designed to understand rather than simply respond.", ["conversation.png"]],
  ["Smart Reminders", "Arlo notices when something is worth remembering and gently offers to help.", ["reminder-offer.png", "reminder-popup.png", "reminder-confirmed.png"]],
  ["Support When You're Stuck", "Feeling stuck doesn't have to stop your day. Arlo helps you choose the smallest possible next step.", ["what-fits-now.png", "support-response.png"]],
  ["Daily Encouragement", "Celebrate wins. Reflect on progress. Come back tomorrow.", ["welcome.png", "welcome-options.png"]],
] as const;

export function ArloProductPage() {
  return <div className="arloLaunch">
    <section className="arloLaunchHero"><div className="container arloLaunchHeroGrid">
      <div className="arloLaunchCopy"><p className="arloLaunchLabel">Now available on Android</p><h1>Meet Arlo<span>Your AI Companion for ADHD</span></h1><p className="arloLaunchSupport">Support that understands.</p><p>Not another productivity app.<br />Just one better step, every day.</p><div className="button-row"><a className="button arloLaunchButton" href={playStoreUrl} target="_blank" rel="noreferrer">Download on Google Play <span>↗</span></a><a className="button arloLaunchGhost" href="#why-arlo">Learn more <span>↓</span></a></div></div>
      <div className="arloLaunchVisual"><div className="arloPromo"><Image src="/arlo/meet-arlo-hero.png" alt="Meet Arlo, your AI companion for ADHD" fill priority sizes="(max-width:900px) 92vw, 650px" /></div><div className="arloPhone"><div className="arloPhoneBar"><Image src="/arlo/app-icon.png" alt="" width={34} height={34} /><strong>Arlo</strong><span>Here with you</span></div><div className="arloChat user">I&apos;m feeling overwhelmed today.<br />I don&apos;t even know where to begin.</div><div className="arloChat reply">That&apos;s okay. You don&apos;t have to figure everything out today.<br /><br /><strong>Let&apos;s just find one small step together.</strong></div><div className="arloComposer">Talk to Arlo… <b>↑</b></div></div></div>
    </div></section>

    <section id="why-arlo" className="arloLaunchSection arloWhy"><div className="container arloSplit"><div><p className="arloLaunchLabel">Why Arlo exists</p><h2>Arlo wasn&apos;t created to make people more productive.</h2><blockquote>“Arlo wasn&apos;t built to help you do more. It was built to help you feel able to take the next step.”</blockquote></div><div className="arloBody"><p>Traditional productivity tools often ask people with ADHD to think differently, work differently and organise differently. For many people, that simply doesn&apos;t work.</p><p>Arlo takes a different approach.</p><ul><li>Instead of pushing harder, Arlo starts by understanding.</li><li>Instead of adding pressure, it reduces it.</li><li>Instead of asking you to become someone else, it works alongside the way your mind already works.</li></ul><p>Whether you&apos;re feeling overwhelmed, anxious, stuck or simply trying to remember life&apos;s endless little tasks, Arlo is there to help you take one better step.</p></div></div></section>

    <section className="arloLaunchSection arloJourney"><div className="container arloSplit"><div><p className="arloLaunchLabel">The journey</p><h2>It began with a simple question.</h2><blockquote>“What if remembering things didn&apos;t have to feel so hard?”</blockquote></div><div className="arloBody"><p>Living with ADHD often means forgetting appointments, losing track of ideas, struggling to start tasks or feeling overwhelmed before the day has even begun.</p><p>Existing tools helped manage calendars and to-do lists. Very few helped manage how people actually felt.</p><p>So we started building something different. Something calmer. Something kinder. Something that listens before it speaks.</p><p>People don&apos;t always need more information. Sometimes they simply need someone to help them take the next step.</p><strong>That philosophy continues to shape every feature we build.</strong></div></div></section>

    <section className="arloLaunchSection arloFeatures"><div className="container"><div className="arloHeading"><p className="arloLaunchLabel">Designed around real ADHD</p><h2>Help that fits the day you&apos;re actually having.</h2></div><div className="arloFeatureGrid">{features.map(([title,text,images],index)=><article className="arloFeature" key={title}><span>0{index+1}</span><div className={`arloScreens arloScreens${images.length}`}>{images.map(image=><Image key={image} src={`/arlo/${image}`} alt={`${title} screen in Arlo`} width={333} height={707}/>)}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="arloLaunchSection arloSetup"><div className="container arloSplit"><div><p className="arloLaunchLabel">A thoughtful beginning</p><h2>Clear from the very first hello.</h2><p>Arlo starts with care: a simple welcome, honest boundaries and privacy explained in plain language. No overwhelming setup.</p></div><div className="arloSetupScreens"><Image src="/arlo/setup.png" alt="Arlo first-run welcome" width={329} height={707}/><Image src="/arlo/setup-details.png" alt="Arlo privacy and support setup" width={333} height={711}/></div></div></section>

    <section className="arloLaunchSection arloWins"><div className="container"><p className="arloLaunchLabel">Built around small wins</p><h2>Life doesn&apos;t usually change overnight.</h2><p className="arloWinsIntro">It changes one small decision at a time.</p><div className="arloWinList"><span>One remembered appointment.</span><span>One completed task.</span><span>One encouraging conversation.</span><span>One deep breath.</span><span>One tiny step.</span></div><h3>Those moments add up.</h3><p>That&apos;s why everything at One Better Labs is built around helping people make one better decision today than they did yesterday.</p></div></section>

    <section className="arloLaunchSection arloMeet"><div className="container arloSplit"><div className="arloMascot"><Image src="/arlo/arlo-mascot.png" alt="Arlo smiling" width={700} height={700}/></div><div><p className="arloLaunchLabel">Meet Arlo</p><h2>A little support can change the shape of a day.</h2><p>Arlo isn&apos;t trying to replace friends, family or professional support. Arlo is simply here when you need a gentle nudge. A reminder. A conversation. A moment to pause. Or someone to help you take the next step.</p></div></div></section>

    <section className="arloLaunchSection arloStudio"><div className="container arloStudioCard"><div><p className="arloLaunchLabel">Built by One Better Labs</p><h2>Thoughtful AI.<br />Real human problems.</h2></div><div><p>One Better Labs exists to build beautifully simple technology that helps people make one better decision.</p><p>Arlo is our first public product. It represents the beginning of a much bigger mission.</p><Link href="/our-story">Read our story <span>→</span></Link></div></div></section>

    <section className="arloLaunchCta"><div className="container"><Image src="/arlo/app-icon.png" alt="Arlo app icon" width={90} height={90}/><h2>Ready to meet Arlo?</h2><p>Download today and discover a calmer way to navigate ADHD.</p><div className="button-row"><a className="button arloLaunchButton" href={playStoreUrl} target="_blank" rel="noreferrer">Download on Google Play <span>↗</span></a><Link className="button arloLaunchGhost" href="/our-story">Learn about One Better Labs <span>→</span></Link></div></div></section>
  </div>;
}
