import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { CTA, Eyebrow, ProductVisual, SectionIntro, Status } from "@/components/ui";
import { products } from "@/data/site";

export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=products.find(x=>x.slug===slug);return p?{title:p.name,description:p.positioning}:{}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products.find(x=>x.slug===slug);if(!p)notFound();return <div className="page-shell"><section className="product-page-hero"><div className="container product-page-hero-grid"><div><Status>{p.status}</Status><h1>{p.name}</h1><p className="positioning">{p.positioning}</p><p className="promise">{p.promise}</p><div className="button-row" style={{marginTop:32}}><Link className="button" href="/contact">Follow the journey <span>↗</span></Link><Link className="button button-ghost" href="/products">All products <span>→</span></Link></div></div><ProductVisual slug={p.slug} name={p.name} number={p.number}/></div></section><section className="content-section"><div className="container editorial-grid"><div><Eyebrow>Built for real life</Eyebrow><h2>Start with the problem. Remove the friction.</h2></div><div className="editorial-copy"><p>{p.audience}</p><p>{p.problem}</p><p>{p.approach}</p></div></div></section><section className="content-section"><div className="container"><SectionIntro eyebrow="Product direction" title="What we’re exploring." text="These capabilities describe the current direction of the product while it remains in development."/><div className="capability-grid">{p.capabilities.map((c,i)=><div className="capability" key={c}><span>0{i+1}</span><p>{c}</p></div>)}</div></div></section><section className="content-section"><div className="container"><SectionIntro eyebrow="Product principles" title={`How ${p.name} should feel.`}/><div className="principle-cards">{p.principles.map(x=><div className="principle-card" key={x.title}><h3>{x.title}</h3><p>{x.text}</p></div>)}</div></div></section><section className="content-section"><div className="container status-panel"><div><Status>{p.status}</Status><h2>Built carefully. Shared honestly.</h2><p>{p.name} is currently in development. Join the OB Labs journey or get in touch to discuss early interest.</p></div><Link className="button" href="/contact">Get in touch <span>↗</span></Link></div></section><CTA/></div>}
